url: "http://blog.itaysk.com"
baseurl: ""
permalink: "/:year/:month/:day/:title"
title: "Itay as a Service"
description: "Itay Shakury's blog"

defaults:
    -
        scope: 
            path: "_posts"
        values:
            layout: "post"

#author profile
author_photo: "/assets/headshot150x150.png"
author_name: "Itay Shakury"
author_bio: "Technology enthusiast, Entrepreneur wannabe."
author_twitter: "itaysk"
author_linkedin: "itaysk"
author_github:  "itaysk"

#this is for seo plugin
twitter:
  username: itaysk

# Build settings
markdown: kramdown
sass:
    style: :compressed

plugins:
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-gist 
    - jekyll-feed

#services
google_analytics: "UA-85195702-1"
#disqus_shortname: "itaysk"

